"""add radpostauth table

Revision ID: bf558a7d25f2
Revises: c863ad7848f8
Create Date: 2025-06-15 20:52:03.676671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf558a7d25f2'
down_revision: Union[str, None] = 'c863ad7848f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radpostauth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('pass', sa.String(length=64), nullable=False),
    sa.Column('reply', sa.String(length=32), nullable=False),
    sa.Column('authdate', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('radpostauth')
    # ### end Alembic commands ###
