"""add radius tables

Revision ID: c863ad7848f8
Revises: 3992dde5f38b
Create Date: 2025-06-15 20:44:41.038112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c863ad7848f8'
down_revision: Union[str, None] = '3992dde5f38b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nasname', sa.String(length=128), nullable=False),
    sa.Column('shortname', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('ports', sa.Integer(), nullable=True),
    sa.Column('secret', sa.String(length=60), nullable=False),
    sa.Column('server', sa.String(length=64), nullable=True),
    sa.Column('community', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('radacct',
    sa.Column('radacctid', sa.BigInteger(), nullable=False),
    sa.Column('acctsessionid', sa.String(length=64), nullable=True),
    sa.Column('acctuniqueid', sa.String(length=32), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('realm', sa.String(length=64), nullable=True),
    sa.Column('nasipaddress', sa.String(length=15), nullable=True),
    sa.Column('nasportid', sa.String(length=15), nullable=True),
    sa.Column('nasporttype', sa.String(length=32), nullable=True),
    sa.Column('acctstarttime', sa.DateTime(), nullable=True),
    sa.Column('acctstoptime', sa.DateTime(), nullable=True),
    sa.Column('acctsessiontime', sa.Integer(), nullable=True),
    sa.Column('acctauthentic', sa.String(length=32), nullable=True),
    sa.Column('connectinfo_start', sa.String(length=32), nullable=True),
    sa.Column('connectinfo_stop', sa.String(length=32), nullable=True),
    sa.Column('acctinputoctets', sa.BigInteger(), nullable=True),
    sa.Column('acctoutputoctets', sa.BigInteger(), nullable=True),
    sa.Column('calledstationid', sa.String(length=50), nullable=True),
    sa.Column('callingstationid', sa.String(length=50), nullable=True),
    sa.Column('acctterminatecause', sa.String(length=32), nullable=True),
    sa.Column('servicetype', sa.String(length=32), nullable=True),
    sa.Column('framedprotocol', sa.String(length=32), nullable=True),
    sa.Column('framedipaddress', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('radacctid'),
    sa.UniqueConstraint('acctuniqueid')
    )
    op.create_table('radcheck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('attribute', sa.String(length=64), nullable=False),
    sa.Column('op', sa.String(length=2), nullable=False),
    sa.Column('value', sa.String(length=253), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('radreply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('attribute', sa.String(length=64), nullable=False),
    sa.Column('op', sa.String(length=2), nullable=False),
    sa.Column('value', sa.String(length=253), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('radreply')
    op.drop_table('radcheck')
    op.drop_table('radacct')
    op.drop_table('nas')
    # ### end Alembic commands ###
