"""Initial migrations

Revision ID: cb00c78f4fd1
Revises: d9fbd9d9e9ab
Create Date: 2025-07-10 21:07:15.593994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb00c78f4fd1'
down_revision: Union[str, Sequence[str], None] = 'd9fbd9d9e9ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###