"""Initial migrations

Revision ID: d9fbd9d9e9ab
Revises: ddf2a28c9d07
Create Date: 2025-07-10 00:20:34.740315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9fbd9d9e9ab'
down_revision: Union[str, Sequence[str], None] = 'ddf2a28c9d07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###